Слить CH-2_user_registration
go-park-mail-ru/2023_2_Chaihona_No.1 pull request #2
Opened 2023-09-30 19:54 UTC by sachatarba

2023-10-07 18:31 UTC, GeorgiyX requested changes

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/handlers.go
> +	Profiles reg.ProfileRepository
Поля нужно сделать не экспортируемыми

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/handlers.go
> +		reg.CreateProfileStorage(),
Сейчас это ок, но в будущем стораджи нужно конструировать снаружи и по указателю передавать  в `CreateRepoHandler `.

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/handlers.go
> +		http.Error(w, `{"error":"wrong_json"}`, 405)
Тут больше подходит Bad Request (400)

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/handlers.go
> +		http.Error(w, `{"error":"wrong_json"}`, 405)
Для кодов ошибок есть константы в `"net/http"`: `http.StatusBadRequest`

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/handlers.go
> +	err = api.Users.RegisterNewUser(&user)
Надо бы провалидировать поля, перед тем как юзера создавать

2023-10-07 18:31 UTC, GeorgiyX commented on registration/signup_form.go
> +}
Анмаршалинг лучше все-таки оставить в коде хендлера. Все операции вокруг разбора байтов запроса нужно проводить в коде хендлера.

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/handlers.go
> +	regForm, err := reg.ParseJSON(r.Body)
Надо относиться со скептицизмом к пришедшему к нам body. Тут мы ожидаем что нам придет json с двумя небольшими строчками логин+пароль, но может случиться так, что нам пару гигабайт вместо этого отправят и мы их все вычитаем в память при разборе JSON. 

Нужно обернуть `Body` перед чтением в [`http.MaxBytesReader`](https://pkg.go.dev/net/http#MaxBytesReader).

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/handlers.go
> +		http.Error(w, `{"error":"user_registration"}`, 400)
В других ПРах отписал, что детали об ошибке стоит записывать на месте обнаружения ошибки и добавлять при этом статус код. Для этого нужен свой тип ошибки.

На этот уровне абстрации нам не ясно 500ку возвращать ли (т.к. у нас база легла) или 400ку, потому-что юзер с таким логином уже зарегестрировался.

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/handlers.go
> +	}
Сейчас ОК, но потом обе эти операции нужно вынести на слой с бизнес-логикой: в хендлере мы  должны лишь работать с http и пердавать/получать данные в точку входа обработки логики.

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/handlers.go
> +		http.Error(w, `{"error":"wrong_json"}`, 405)
BadRequest

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/handlers.go
> +
Обычно не добавляют пустую строку между вызовом функции и обработкой ошибки из этой функции.

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/handlers.go
> +}
У нас все общение через JSON'ы)

2023-10-07 18:31 UTC, GeorgiyX commented on main.go
> +	http.HandleFunc("/", rep.Root)
`/` - это очень странный метод api, стоит дать норм. название (если этот метод вообще нужен)

2023-10-07 18:31 UTC, GeorgiyX commented on main.go
> +	}()
Тестовых пользователей и профили стоит создавать в конструкторе стораджей.

2023-10-07 18:31 UTC, GeorgiyX commented on main.go
> +	}()
Или это на хадлер тесты такие?) Тогда стоит использовать [`"net/http/httptest"`](https://pkg.go.dev/net/http/httptest).

2023-10-07 18:31 UTC, GeorgiyX commented on main.go
> +	http.HandleFunc("/", rep.Root)
В ветке CH-6_project_base у всех урлов префикс `/api/v1/l`, давай тут также сделаем.

2023-10-07 18:31 UTC, GeorgiyX commented on .gitignore
> +go.mod
go.mod нужен в репе

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/errors_autorization.go
> +var ErrWrongPassword = errors.New("Wrong password!")
Вообще принято текст ошибки писать с маленькой буквы и без знаков препинания на конце, т.к. очень часто ошибки, по мере прокидывания ошибки по стеку вызовов,  "заворачивают" друг в друга через [`errors.Wrap`](https://pkg.go.dev/github.com/pkg/errors#Wrap).  В логах в итоге в логах получается текст вроде этого: `handler: usecase: wrong login`

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/errors_autorization.go
> +var ErrWrongPassword = errors.New("Wrong password!")
И вы тоже пользуйтесь этим пакетом)

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/login_form.go
> +	Body_ BodyLogin `json:"body"`
Зачем `_`?

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/login_form.go
> +	newUserInput := new(LoginForm)
Лучше использовать `new`, только если без него не обойтись. В остальных случаях используем `&` (`&LoginForm{}`).

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/login_form.go
> +	newUserInput := new(LoginForm)
Ниже отписал, что анмаршалинг стоит все-таки оставить в хенделере

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/login_form_test.go
> +}
Выглядит как тесты на функционал стандартной либы

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/login_form_test.go
> +}
Для проверки условий в тестах используем [require](https://pkg.go.dev/github.com/stretchr/testify/require)

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/rand_string.go
> +}
Для генерации тестовых данных можно использовать либу, например: github.com/brianvoe/gofakeit

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage.go
> +	val, ok := storage.Sessions[sessionId]
Для таких ситуаций (когда нам нужен доступ только на чтение), стоит использовать `sync.RWMutex`.

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage.go
> +	Size     uint32
Зачем нам это поле? Размер мапки можем получить через `len()`

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage.go
> +		return &copy, true
Зачем тут копию создавать? И почему по указателю возвращаем?

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage.go
> +	sessions := make([]Session, 0)
Можно сразу выделить буфер нужного размера

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage_test.go
> +	} else {
`requare.NoError`

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage_test.go
> +	} else {
Вообще в таком случае `else` не нужен, тест и так дальше не пойдет

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage_test.go
> +	}
Обычно для тестов заводят структуру данных, которая будет хранить все необходимые для теста объекты - моки, стораджи и методы для их инициализации. А в коде теста только вызывают проверяемые методы и выполняют ассерты.

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage_test.go
> +					m.Unlock()
Для таких случаев есть [`"sync/atomic"`](https://pkg.go.dev/sync/atomic)

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage_test.go
> +				if val.SessionId != session.SessionId || val.UserId != session.UserId {
Большая вложенность кода, проверять лучше негативный кейс, а оператором else не пользоваться

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage_test.go
> +	}
Если есть желание обнаруживать состояние "гонки" (не синхронизированный доступ к один тем же данным их разных горутин), то стоит воспользоваться флагом race (`go test -race`). А в тестах эмулировать параллельную нагрузку.

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage_test.go
> +		}(i, &m)
Зачем мьютекс явно передавать по ссылке, если он и так захватывается горутиной?

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage_test.go
> +	const SESSIONS = 100
Повторяется константа, можно вынести на уровень пакета.

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/session_storage_test.go
> +package authorization
`package authorization_test`

2023-10-07 18:31 UTC, GeorgiyX commented on authorization/utils.go
> +	}
Давайте не забудем во втором РК что пароли не в открытом виде хранятся

2023-10-07 18:31 UTC, GeorgiyX commented on model/goal.go
> +const RubCurrency = "rub"
Вроде нигде не используется. Что это?

2023-10-07 18:31 UTC, GeorgiyX commented on registration/profile_repository.go
Repository или все же Storage?

2023-10-07 18:31 UTC, GeorgiyX commented on registration/profile_storage.go
Тут надо поправить тоже что и в сессиях

2023-10-07 18:42 UTC, GeorgiyX commented on authorization/utils.go
> +	SID := RandStringRunes(SID_LEN)
Для генерации случайной строки лучше использовать uuid

2023-10-07 18:48 UTC, GeorgiyX commented on authorization/utils.go
> +	})
`Secure: true`  и еще `SameSite` стоит указать

2023-10-07 18:49 UTC, GeorgiyX commented on authorization/rand_string.go
> +}
А увидел, что это для сессий. Отписал там где используется.

2023-10-07 19:04 UTC, GeorgiyX commented on authorization/session_storage_test.go
> +func TestRegisterNewSession(t *testing.T) {
Стоит сделать вызов `t.Parallel()` - тесты в модуле будут запускаться параллельно.

2023-10-07 19:10 UTC, GeorgiyX commented on authorization/session_storage.go
> +	}
Стоит все поля явно инициализировать (или не инициализировать вообще ни одного)

2023-10-08 14:14 UTC, sachatarba commented on authorization/session_storage.go
> +	Size     uint32
Я его добавил на случай, если придется сделать поле sessions не экспортируемым (по хорошему, как мне кажется, извне к нему в принципе не должно быть доступа, потому что это может привести к тому, что кто-то залезет в мапку,  не заблокировав mutex, и получится гонка)

2023-10-08 14:25 UTC, sachatarba commented on authorization/session_storage.go
> +		return &copy, true
По указателю возвращаю, чтобы в случае ошибки можно было бы вернуть вместо структуры nil, и вызывающая сторона точно не получила неправильных данных (возможно, пустую структуру вернуть тоже нормальный вариант, но я в этом не был уверен). Копию создаю, чтобы не получать гонок (доступ по указателю к объекту внутри мапы), тут тоже я не был уверен, что это создает гонки в принципе, но решил перестраховаться

2023-10-09 18:53 UTC, GeorgiyX commented on authorization/session_storage.go
> +	Size     uint32
Насчет того чтобы сделать Sessions не экспортируемым это ты верно подметил.
Но и к Size тоже не надо открывать доступ - для этого можно сделать метод.

2023-10-09 21:17 UTC, sachatarba commented on handlers/handlers.go
> +		http.Error(w, `{"error":"user_registration"}`, http.StatusBadRequest)
`{"error":"user_authorization"}`

2023-10-09 22:48 UTC, sachatarba commented on handlers/handlers.go
> +	auth.RemoveSession(w, api.sessions, session.Value)
Если куки нет, то session - nil (при этом err тоже nil) - возникает паника при разыменовании. Надо решить как обрабатывать такую ситуацию

2023-10-14 21:10 UTC, GeorgiyX commented on authorization/login_form_test.go
> +}
Где-то уже писал что лучше вообще  от ParseJSON избавиться

2023-10-14 21:11 UTC, GeorgiyX commented on authorization/rand_string.go
> +func RandStringRunes(n int) string {
Сейчас уже не используется, давай удалим

2023-10-14 21:14 UTC, GeorgiyX commented on authorization/session_storage.go
> +	Size     uint32
Вообще мысль которую хотел донести - нет необходимости хранить и поддерживать `Size`. Если нам нужно знать размер число сессий, то делаем метод `Size() int` который под капотом будет возвращать `len(storage. Sessions)`.

2023-10-14 21:17 UTC, GeorgiyX commented on authorization/session_storage.go
> +		return &copy, true
Гонки тут не будет,`val` - это копия объекта хранящегося в `Sessions` по ключу `sessionId`.

2023-10-14 21:20 UTC, GeorgiyX commented on authorization/session_storage.go
> +		return &copy, true
> возможно, пустую структуру вернуть тоже нормальный вариант

Да это норм вариант. Пользователь метода `CheckSession` должен по `bool`'у (в других случаях по error'у) определять можно ли работать с сессией или нет.

2023-10-14 21:23 UTC, GeorgiyX commented on authorization/session_storage.go
> +	}
`make([]Session, 0, len(storage.Sessions))`, а в цикле `sessions = append(sessions, session)`

2023-10-14 21:25 UTC, GeorgiyX commented on authorization/session_storage.go
> +	}
или `make([]Session, len(storage.Sessions))`  + `copy(sessions, storage.Sessions)`

2023-10-14 21:31 UTC, GeorgiyX commented on handlers/handlers.go
> +	defer body.Close()
Нет необходимости (движок сервера сам закроет). Это кстати есть в комментариях к коду `http.Request` (полезно посматривать туда).

2023-10-14 21:41 UTC, GeorgiyX commented on handlers/handlers.go
> +		w.WriteHeader(http.StatusOK)
После первого w.Write() статус код писать уже поздно (заголовок со статусом должен идти в буфере ответа до body). При вызове `json.NewEncoder(w).Encode(...)` как раз и вызывается `Write`, в таком случае записывается статус код по умолчанию - 200 OK.

2023-10-14 21:42 UTC, GeorgiyX commented on handlers/handlers.go
> +	} else {
Вместо `else` и +1 уровня вложенности кода, лучше делать `return`

2023-10-14 21:43 UTC, GeorgiyX commented on handlers/tests/handlers_test.go
> +	for caseName, testCase := range SignupTestCases {
`t.Parallel()`

2023-10-14 21:46 UTC, GeorgiyX commented on registration/profile_repository.go
> +	RegisterNewProfile(user *model.Profile) *ErrorRegistration
Почему `*ErrorRegistration`, а не `error`?

2023-10-14 21:59 UTC, GeorgiyX commented on handlers/handlers.go
> +			http.Error(w, `{"error":"json_encoding"}`, http.StatusInternalServerError)
Если упали на записи body запроса - уже ничего не поделаешь и статус код ошибки тоже не отправить (см. выше). Остается только залоггировать ошибку.

2023-10-14 22:01 UTC, GeorgiyX commented on handlers/handlers.go
> +	auth.RemoveSession(w, api.sessions, session.Value)
Если сессии нет - кидаем Unauthorized 401

2023-10-15 12:17 UTC, GeorgiyX commented on handlers/handlers.go
> +		log.Fatal(err)
Тоже что и в предыдущем МРе

2023-10-15 16:33 UTC, GeorgiyX approved these changes

2023-10-16 11:42 UTC, merged